events {}

http {
    upstream backend {
        server app1:80 max_fails=1 fail_timeout=3s;
        server app2:80 max_fails=1 fail_timeout=3s;
        server app3:80 max_fails=1 fail_timeout=3s;
    }

    server {
        listen 80;

        location / {
            proxy_next_upstream error timeout http_503;
            proxy_pass http://backend;
        }
    }
}
